version: '3'

services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongo
    networks:
      - app-backend

  mongo:
    image: mongo
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    volumes:
      - $PWD/db:/data/db
    networks:
      - app-backend

  broker-mqtt:
    image: vernemq/vernemq
    container_name: mqtt
    environment:
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
    ports:
      - "1883:1883"
    networks:
      - app-backend

  backend:
    image: app-backend
    container_name: app-backend
    build: $PWD
    ports:
      - "5000:5000"
      - "80:80"
      - "443:443"
    networks:
      - app-backend

networks: 
    app-backend:
      driver: bridge